name: Node CI

on: [push]

jobs:
  Terraform-CI:
    name: Terraform-CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: ci
    - run: npm test